const products = [
    {
        id : 0,
        name: "ASICS – GEL NANDI SMOKE GREY SWAMP GREEN",
        price: 80.00,
        img_src: "images/product-1.jpg",
        pno: 101,
        info: "products-info-1.html",
    },
    {
        id : 1,
        name: "SALOMON — XA-PRO FUSION ADVANCED ",
        price: 159.99,
        img_src: "images/product-2.jpg",
        pno: 102,
        info: "products-info-2.html",
    },
    {
        id : 2,
        name: "CONVERSE – CHUCK 70 UNIVERSITY BLUE EGRET BLACK",
        price: 99.99,
        img_src: "images/product-3.jpg",
        pno: 103,
        info: "products-info-3.html",
    },
    {
        id : 3,
        name: "SALOMON – XT-6 ADVANCED PRIMROSE",
        price: 50.00,
        img_src: "images/product-4.jpg",
        pno: 104,
        info: "products-info-4.html",
    },
    {
        id : 4,
        name: "CONVERSE X RICK OWENS – DRKSTR CHUCK 70 OX BLACK",
        price: 100.00,
        img_src: "images/product-5.jpg",
        pno: 105,
        info: "products-info-5.html",
    },
    {
        id : 5,
        name: "CONVERSE – WEAPON CX MID EGRET DARK RED",
        price: 59.99,
        img_src: "images/product-6.jpg",
        pno: 106,
        info: "products-info-6.html",
    },
    {
        id : 6,
        name: "RAF SIMONS — CYLON WHITE/PINK",
        price: 65.00,
        img_src: "images/product-7.jpg",
        pno: 107,
        info: "products-info-7.html",
    },
    {
        id : 7,
        name: "RAF SIMONS — CYLON BLACK/PINK",
        price: 84.99,
        img_src: "images/product-8.jpg",
        pno: 108,
        info: "products-info-8.html",
    },
    {
        id : 8,
        name: "MONCLER — GRENOBLE RECYCLED HUGO SHOES",
        price: 92.00,
        img_src: "images/product-9.jpg",
        pno: 109,
        info: "products-info-9.html",
    },
    {
        id : 9,
        name: "ASICS – GEL NANDI SMOKE GREY SWAMP GREEN",
        price: 68.00,
        img_src: "images/product-10.jpg",
        pno: 110,
        info: "products-info-10.html",
    },
    {
        id : 10,
        name: "RAF SIMONS – CYLON 22 ANTRACITE",
        price: 50.00,
        img_src: "images/product-11.jpg",
        pno: 111,
        info: "products-info-11.html",
    },
    {
        id : 11,
        name: "RAF SIMONS – CYLON 21 - WHITE",
        price: 90.00,
        img_src: "images/product-12.jpg",
        pno: 112,
        info: "products-info-12.html",
    },
    {
        id : 12,
        name: "CONVERSE – CLIMATE ESCAPISM CHUCK 70 SEDONA",
        price: 88.00,
        img_src: "images/product-13.jpg",
        pno: 113,
        info: "products-info-13.html",
    },
    {
        id : 13,
        name: "CONVERSE X FENG CHEN WANG – CHUCK 70 2 IN 1 HIGH",
        price: 75.00,
        img_src: "images/product-14.jpg",
        pno: 114,
        info: "products-info-14.html",
    },
    {
        id : 14,
        name: "SALOMON – XT-4 ADVANCED BLUE NIMBUS CLOUD",
        price: 105.99,
        img_src: "images/product-15.jpg",
        pno: 115,
        info: "products-info-15.html",
    },
    {
        id : 15,
        name: "CONVERSE – WEAPON CX MID EGRET LIGHT TWINE",
        price: 45.00,
        img_src: "images/product-16.jpg",
        pno: 116,
        info: "products-info-16.html",
    },
]
